### ISSUE TITLE
How to install clusterProfiler.dplyr package

### ISSUE THREAD

**Issue by hexingkang1990** [YuLab-SMU/clusterProfiler.dplyr#1]
Hi Prof. Yu

I recently read your book "clusterProfiler: universal enrichment tool for functional and comparative study" and want to use package "clusterProfiler.dplyr". However, I could not fine the way to install this package?  Could you provide me a way to install it?   Thanks

Bests,
Xingkang.

**Comment by GuangchuangYu** [comment]
search how to install r package from github, and you can get the answer.

**Comment by hexingkang1990** [comment]
Thanks a lot. I get it.

**Comment by davetang** [comment]
For those wondering about the installation step.

```r
# if you don't have devtools installed, run
# install.packages("devtools")

devtools::install_github("YuLab-SMU/clusterProfiler.dplyr")
```
